name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    
    - name: Build the Docker image
      run: |
        TIMESTAMP=$(date +%s)
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:$TIMESTAMP
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:$TIMESTAMP ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:latest
    
    - name: Push to Docker Hub
      if: github.event_name != 'pull_request'
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:$(date +%s)
